#!/bin/bash

# Prefix for included source files
SRC_PREFIX=${0%/*}

source $SRC_PREFIX/include_files

TMP_FILE=".deployfiles"

# Clear tmp file
> $TMP_FILE

# Find valid files from pattern
for i in "${FILE_TYPES[@]}"
do
        find . -name "*$i" >> $TMP_FILE
done

# Delete files
find . -type f | grep -vx -f $TMP_FILE | xargs rm

# Delete empty directories
find . -type d -empty -delete
